version: '3'

volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:10.6
    environment:
      POSTGRES_USER: quasars
      POSTGRES_PASSWORD: password
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  quasars:
    image: "kineticdial/quasars:${QUASARS_VERSION}"
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - /var/www/quasars
    env_file:
      - .quasars.env
