version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose build
      - run: docker-compose run quasars bin/rails db:migrate RAILS_ENV=test
      - run:
          name: Docker Push
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker tag kineticdial/quasars:latest kineticdial/quasars:$(git rev-parse --short HEAD)
            docker push kineticdial/quasars:latest
            docker push kineticdial/quasars:$(git rev-parse --short HEAD)
  test:
    docker:
      - image: circleci/ruby:2.6.0
    steps:
      - checkout
      - setup_remote_docker
      - run: docker pull kineticdial/quasars:$(git rev-parse --short HEAD)
      # - run: docker-compose run quasars bin/rails db:migrate RAILS_ENV=test
      - run: QUASARS_VERSION=$(git rev-parse --short HEAD) docker-compose -f docker-compose.ci.yml run quasars rake

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
